name: Java Autograding - Assignment 1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-grade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compile Java program
      run: javac Assignment2/CSVPreprocessing.java

    - name: Run the program and capture output
      run: |
        mkdir -p output
        java Assignment2.CSVPreprocessing > output/result.txt

    - name: Initialize grading variables
      id: grading
      run: |
        points_available=17
        points_awarded=0

        check_line() {
          if grep -Fxq "$1" output/result.txt; then
            echo "✅ Found: $1"
            points_awarded=$((points_awarded+1))
          else
            echo "❌ Missing: $1"
          fi
        }

        # Task 1 lines
        check_line "=== Task 1: Count valid rows and remove N/A / null rows==="
        check_line "Final number of valid rows: 5"

        # Task 2 lines
        check_line "=== Task 2: Binning by Boundaries (2 bins) ==="
        check_line "Bin 1: [67.0, 85.0]"
        check_line "67.0 -> 67.0"
        check_line "78.0 -> 85.0"
        check_line "85.0 -> 85.0"
        check_line "Bin 2: [89.0, 95.0]"
        check_line "89.0 -> 89.0"
        check_line "95.0 -> 95.0"

        # Task 3 lines
        check_line "=== Task 3: Normalization [0, 1] ==="
        check_line "Original: 67.00 -> Normalized: 0.00"
        check_line "Original: 78.00 -> Normalized: 0.39"
        check_line "Original: 85.00 -> Normalized: 0.64"
        check_line "Original: 89.00 -> Normalized: 0.79"
        check_line "Original: 95.00 -> Normalized: 1.00"

        echo "points_awarded=$points_awarded" >> $GITHUB_ENV
        echo "points_available=$points_available" >> $GITHUB_ENV

    - name: Display grading result
      run: |
        echo "Points Awarded: $points_awarded / $points_available"

    - name: Add summary for GitHub Actions UI
      run: |
        echo "### Grading Result" >> $GITHUB_STEP_SUMMARY
        echo "**Points Awarded:** $points_awarded / $points_available" >> $GITHUB_STEP_SUMMARY

    - name: Display result file (for debug)
      if: always()
      run: cat output/result.txt
